- name: playbook
  hosts: web.unity.rc.umass.edu
  tasks:
    - name: role
      include_role:
        name: "{{ this_role }}"
      loop:
        - shibboleth-discovery
      loop_control:
        loop_var: this_role
